name: Storage Sync
on:
#   push:
#     branches: [ "master" ]
  workflow_dispatch:
jobs:  

  checkout_linux_runner:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v3 
  
  CallworkflowAUTH:
    needs: checkout_linux_runner
    uses: araju-sinha/gcloud_bucket_sync/.github/workflows/Auth_reusable_wf.yml@master
    
  
  RSYNC:
    runs-on: ubuntu-latest
    needs: CallworkflowAUTH
    steps:
     - name: "yml to json"
       run: echo "hello"
     - name: "cloud sync"
       run: 'gsutil rsync -R -c ./folder1 gs://github_action/testing'
      
#       - name: "store file as secret"  
#         run: |
#          echo "$gcs_SECRET >> gcs_credentials.json"
#          ls -ltr
#          cat gcs_credentials.json
#         env:
#           gcs_SECRET: ${{ secrets.gcp_credentials }}
 
#       - id: 'auth'
#         name: 'Authenticate to Google Cloud'
#         uses: 'google-github-actions/auth@v1'
#         with:
#           credentials_json: ${{ secrets.gcp_credentials }}
 
#       - name: 'Set up Cloud SDK'
#         uses: 'google-github-actions/setup-gcloud@v1'

#       - name: 'GCP SETUP'
#         uses: 'google-github-actions/setup-gcloud@v0.6.0'
#         with:
#           project_id: 'flash-span-372817'

      

      
